# Generated by Django 6.0.2 on 2026-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('CONDUCTOR', 'Conductor'), ('CLIENTE', 'Cliente')], max_length=20),
        ),
    ]
