# Generated by Django 6.0.2 on 2026-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(default='TEMP123', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
