# Generated by Django 6.0.2 on 2026-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(default='DEFAULT001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
